#!/bin/bash

# Create production build
npm run build

# Commit dist folder to temp branch
git checkout -b temp-deploy
git add -f dist
git commit -m "Auto deploy"

# create a local gh-pages branch containing new build
git subtree split --prefix dist -b gh-pages

# force the push of the gh-pages branch to the remote gh-pages branch at origin
git push -f origin gh-pages:gh-pages

# clean temprorary branches
git branch -D gh-pages
git checkout master
git branch -D temp-deploy
